/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import java.awt.Cursor;
import java.util.HashMap;
import javax.swing.JOptionPane;



/**
 *
 * @author kintanara_cis21035
 */
public class NewJFrame extends javax.swing.JFrame {

    HashMap<String, String> userInfo =  new HashMap<>();
    
    public NewJFrame() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnRst = new javax.swing.JButton();
        btnAddUsr = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        FNTF = new javax.swing.JTextField();
        LNTF = new javax.swing.JTextField();
        BDTF = new javax.swing.JTextField();
        EMTF = new javax.swing.JTextField();
        CNTF = new javax.swing.JTextField();
        ADTF = new javax.swing.JTextField();
        photoObj = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnAddPhoto = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        IDTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        userList = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        srchTF = new javax.swing.JTextField();
        btnSrchUsr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Forms");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));
        jPanel1.setForeground(new java.awt.Color(240, 240, 240));

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSave.setBackground(new java.awt.Color(102, 255, 204));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSave.setText("Update");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSaveMouseEntered(evt);
            }
        });
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnRst.setBackground(new java.awt.Color(102, 255, 204));
        btnRst.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRst.setText("Reset");
        btnRst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRstMouseEntered(evt);
            }
        });
        btnRst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRstActionPerformed(evt);
            }
        });

        btnAddUsr.setBackground(new java.awt.Color(102, 255, 204));
        btnAddUsr.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAddUsr.setText("Add User");
        btnAddUsr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddUsrMouseEntered(evt);
            }
        });
        btnAddUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUsrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(btnSave)
                .addGap(121, 121, 121)
                .addComponent(btnAddUsr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(btnRst)
                .addGap(95, 95, 95))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnRst)
                    .addComponent(btnAddUsr))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setForeground(new java.awt.Color(240, 240, 240));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("First Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Last Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Birth Date:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("E-mail:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Contact #:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Address:");

        FNTF.setBackground(new java.awt.Color(204, 255, 204));

        LNTF.setBackground(new java.awt.Color(204, 255, 204));

        BDTF.setBackground(new java.awt.Color(204, 255, 204));

        EMTF.setBackground(new java.awt.Color(204, 255, 204));

        CNTF.setBackground(new java.awt.Color(204, 255, 204));

        ADTF.setBackground(new java.awt.Color(204, 255, 204));

        photoObj.setBackground(new java.awt.Color(204, 255, 204));
        photoObj.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));

        javax.swing.GroupLayout photoObjLayout = new javax.swing.GroupLayout(photoObj);
        photoObj.setLayout(photoObjLayout);
        photoObjLayout.setHorizontalGroup(
            photoObjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 187, Short.MAX_VALUE)
        );
        photoObjLayout.setVerticalGroup(
            photoObjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 152, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Photo:");

        btnAddPhoto.setBackground(new java.awt.Color(102, 255, 204));
        btnAddPhoto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAddPhoto.setText("Add Photo");
        btnAddPhoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddPhotoMouseEntered(evt);
            }
        });
        btnAddPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPhotoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("ID:");

        IDTF.setBackground(new java.awt.Color(204, 255, 204));
        IDTF.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jScrollPane1.setBackground(new java.awt.Color(204, 255, 204));

        userList.setBackground(new java.awt.Color(204, 255, 204));
        userList.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        userList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "1", "2", "3", "4", "5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        userList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        userList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(userList);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(3, 3, 3))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(1, 1, 1)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LNTF, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                                .addComponent(FNTF)
                                .addComponent(BDTF)
                                .addComponent(IDTF))
                            .addComponent(EMTF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CNTF)
                            .addComponent(ADTF, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(photoObj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnAddPhoto)
                        .addGap(53, 53, 53)))
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(IDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(FNTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LNTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(EMTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CNTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 6, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(photoObj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30))
                                    .addComponent(btnAddPhoto, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ADTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(153, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Form");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Search:");

        srchTF.setBackground(new java.awt.Color(204, 255, 204));

        btnSrchUsr.setBackground(new java.awt.Color(102, 255, 204));
        btnSrchUsr.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSrchUsr.setText("Search User");
        btnSrchUsr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSrchUsrMouseEntered(evt);
            }
        });
        btnSrchUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSrchUsrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(217, 217, 217))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(srchTF)
                .addGap(8, 8, 8)
                .addComponent(btnSrchUsr)
                .addGap(22, 22, 22))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(srchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSrchUsr))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(FNTF.getText().compareTo("") == 0){
            JOptionPane.showMessageDialog(rootPane, "Fields should not be Empty!", "Empty Fields", JOptionPane.WARNING_MESSAGE);
        }
        else if(LNTF.getText().compareTo("") == 0){
            JOptionPane.showMessageDialog(rootPane, "Fields should not be Empty!", "Empty Fields", JOptionPane.WARNING_MESSAGE);
        }
        else if(BDTF.getText().compareTo("") == 0){
            JOptionPane.showMessageDialog(rootPane, "Fields should not be Empty!", "Empty Fields", JOptionPane.WARNING_MESSAGE);
        }
        else if(EMTF.getText().compareTo("") == 0){
            JOptionPane.showMessageDialog(rootPane, "Fields should not be Empty!", "Empty Fields", JOptionPane.WARNING_MESSAGE);
        }
        else if(CNTF.getText().compareTo("") == 0){
            JOptionPane.showMessageDialog(rootPane, "Fields should not be Empty!", "Empty Fields", JOptionPane.WARNING_MESSAGE);
        }
        else if(ADTF.getText().compareTo("") == 0){
            JOptionPane.showMessageDialog(rootPane, "Fields should not be Empty!", "Empty Fields", JOptionPane.WARNING_MESSAGE);
        }
        else{
            
            userInfo.put("firstName", FNTF.getText().trim());
            userInfo.put("lastName", LNTF.getText().trim());
            userInfo.put("birthDate", BDTF.getText().trim());
            userInfo.put("email", EMTF.getText().trim());
            userInfo.put("contactNo", CNTF.getText().trim());
            userInfo.put("address", ADTF.getText().trim());
            JOptionPane.showMessageDialog(rootPane, "Information has been Saved", "Information Saved", JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnRstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRstActionPerformed
        srchTF.setText("");
        FNTF.setText("");
        LNTF.setText("");
        BDTF.setText("");
        EMTF.setText("");
        CNTF.setText("");
        ADTF.setText("");
        JOptionPane.showMessageDialog(rootPane, "Fields has been Reset", "Field Reset", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnRstActionPerformed

    private void btnAddPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPhotoActionPerformed
        
    }//GEN-LAST:event_btnAddPhotoActionPerformed

    private void btnRstMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRstMouseEntered
        btnRst.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnRstMouseEntered

    private void btnSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseEntered
        btnSave.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnSaveMouseEntered

    private void btnAddPhotoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddPhotoMouseEntered
        btnAddPhoto.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnAddPhotoMouseEntered

    private void btnAddUsrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddUsrMouseEntered
       btnAddUsr.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnAddUsrMouseEntered

    private void btnSrchUsrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSrchUsrMouseEntered
        btnSrchUsr.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnSrchUsrMouseEntered

    private void btnSrchUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSrchUsrActionPerformed
        if(srchTF.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Search Field is Empty", "Empty Search Field", JOptionPane.WARNING_MESSAGE);
        }
        else{
            
        }
    }//GEN-LAST:event_btnSrchUsrActionPerformed

    private void btnAddUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUsrActionPerformed
        if(IDTF.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Fields should not be Empty!", "Empty Fields", JOptionPane.WARNING_MESSAGE);
        }
        else if(FNTF.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Fields should not be Empty!", "Empty Fields", JOptionPane.WARNING_MESSAGE);
        }
        else if(LNTF.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Fields should not be Empty!", "Empty Fields", JOptionPane.WARNING_MESSAGE);
        }
        else if(BDTF.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Fields should not be Empty!", "Empty Fields", JOptionPane.WARNING_MESSAGE);
        }
        else if(EMTF.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Fields should not be Empty!", "Empty Fields", JOptionPane.WARNING_MESSAGE);
        }
        else if(CNTF.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Fields should not be Empty!", "Empty Fields", JOptionPane.WARNING_MESSAGE);
        }
        else if(ADTF.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Fields should not be Empty!", "Empty Fields", JOptionPane.WARNING_MESSAGE);
        }
        else{
            userInfo.put("ID", IDTF.getText().trim());
            userInfo.put("firstName", FNTF.getText().trim());
            userInfo.put("lastName", LNTF.getText().trim());
            userInfo.put("birthDate", BDTF.getText().trim());
            userInfo.put("email", EMTF.getText().trim());
            userInfo.put("contactNo", CNTF.getText().trim());
            userInfo.put("address", ADTF.getText().trim());
            
            JOptionPane.showMessageDialog(rootPane, "Information has been Saved", "Information Saved", JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_btnAddUsrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ADTF;
    private javax.swing.JTextField BDTF;
    private javax.swing.JTextField CNTF;
    private javax.swing.JTextField EMTF;
    private javax.swing.JTextField FNTF;
    private javax.swing.JTextField IDTF;
    private javax.swing.JTextField LNTF;
    private javax.swing.JButton btnAddPhoto;
    private javax.swing.JButton btnAddUsr;
    private javax.swing.JButton btnRst;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSrchUsr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel photoObj;
    private javax.swing.JTextField srchTF;
    private javax.swing.JList userList;
    // End of variables declaration//GEN-END:variables
}
